# This is a basic workflow that is manually triggered

name: Manual execution Bundesnetzagentur

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  installieren:
    runs-on: ubuntu-latest
    steps:      
      - name: Checkout latest version
        uses: actions/checkout@v2
      - name: Installiere notwendige Pakete 
        run:  |
          sudo apt-get install wget
          pip install folium==0.12.1
          pip install pandas
          pip install openpyxl
          pip install geojson   
      - name: Create Geojson BNA
        run: python src/server/create_geojson_bna.py 
      - name: setup git config
        run: |
          git config user.name "GitHub Actions Bot"    # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
          git config user.email "<>"
      - name: commit update
        run: |
          git add index.html
          git add free_chargers_DE.geojson
          git commit -m "Update from source data."
          git push # -u origin master    # Stage the file, commit and push
